### ISSUE TITLE
Crashes while creating template under Windows

### ISSUE THREAD

**Issue by Gregg8** [ducky427/electron-template#1]
Under Windows 8.1 (and lein 2.5.1) , I typed `lein new electron electron-test` but it exceptions. Here is the relevant part of the output...

```
Retrieving electron/lein-template/0.1.0/lein-template-0.1.0.pom from clojars
Retrieving electron/lein-template/0.1.0/lein-template-0.1.0.jar from clojars
Generating fresh 'lein new' electron project.
java.lang.IllegalArgumentException: No implementation of method: :make-input-stream of protocol: #'clojure.java.io/IOFactory found for class: nil
 at clojure.core$_cache_protocol_fn.invoke (core_deftype.clj:544)
    clojure.java.io$fn__8615$G__8606__8622.invoke (io.clj:69)
    clojure.java.io$input_stream.doInvoke (io.clj:136)
etc.
```

any thoughts?

**Comment by ducky427** [comment]
Thanks. I've just deployed a fix to this issue. Let me know if you experience it now.

**Comment by Gregg8** [comment]
I do still get the same error.

**Comment by ducky427** [comment]
@Gregg8, did the template upgrade to v0.1.1?

[edit] I tried it on windows cmd prompt, and it worked for me. hmm..

**Comment by Gregg8** [comment]
It produces no files, not even the folder I specify (electron-test, also tried electrontest) so I can't tell

**Comment by ducky427** [comment]
Hi @Gregg8, I can't seem to reproduce this. but I am testing this on a Windows 8.1 VM.

Could you help me to debug this? It shouldn't take more than 15 minutes.

Steps:
1. Delete the existing electron template from local maven repo. So delete the folder: `C:\Users\<user>\.m2\repository\electron`.
2. Clone this repo and switch to the `develop` branch.
3. In `electron-template` folder and type: `lein install`. This will install the template into your maven repo.
4. In another location, try using the template: `lein new electron <template-name>`.

The last command will produce some output. Could you share that with me?

Thanks

**Comment by ducky427** [comment]
Please reopen this if you think this is still an issue
