### ISSUE TITLE
Where do we write backend stuff?

### ISSUE THREAD

**Issue by slhsen** [ducky427/electron-template#10]
Hi,

Where can I write backend node.js stuff like

``` clojure
(def path (nodejs/require "path"))
(def Electron (nodejs/require "electron"))
(def BrowserWindow (.-BrowserWindow Electron))
(def crash-reporter (.-crashReporter Electron))
(def Os (nodejs/require "os"))
(def *win* (atom nil))
(def app (.-app Electron))
```

As far as I can see [descjop](https://github.com/karad/lein_template_descjop) leiningen template creates two separate directories for backend and frontend code like my_project/src and my_project/src_front but I couldn't find that distinction in this project.

Closest thing I can find is app/app.js file but that means I have to write plain javascpript to handle things like saving state etc :(

**Comment by sgnl** [comment]
`electron_src` > `electron` > `core.cljs`

**Comment by slhsen** [comment]
I should have answered this earlier but here it is: It turns out there is no need to separate backend stuff from the rest of the code (At least not in a special folder). Here is how I did it:

1. Created a namespace for common file operations:
``` clojure
(ns my-project.nodejs)

;(defonce path (js/require "path"))
(defonce fs (js/require "fs"))

(defn slurp [file]
  "Read file and return contents as string"
  (.toString  (.readFileSync fs file)))

(defn file-exists? [file]
  (.existsSync fs file))

(defn spit [file contents]
  "Write contents to file"
  (.writeFileSync fs file contents))
```

2. Then just use it:
``` clojure
(ns my-project.entry-store
  (:require [cljs.reader :as reader]
            [my-project.nodejs :as nodejs]
            [my-project.entry :as entry]))

(defn- load-from-file []
  (if (nodejs/file-exists? filePath)
    (into (sorted-map) (string-to-entries (nodejs/slurp filePath)))
    (println (str "File not found" filePath))))

(defn save! [entry-store]
  (nodejs/spit filePath (pr-str entry-store))
  (println (str "Entries saved to: " filePath)))

```
