### ISSUE TITLE
CMD-R does not work most of the time

### ISSUE THREAD

**Issue by ghost** [ducky427/electron-template#2]
Sometimes CMD-R (Reload Page) does not work.

**Comment by ducky427** [comment]
I don't think the template is doing anything special for controlling CMD-R and this is being handled by Electron. 

I'll upgrade the template to use the latest Electron. Beyond that it may be an Electron issue.

Thanks for reporting this.

**Comment by ducky427** [comment]
I've just released a new version of the template if the latest dependencies. Hopefully this issue has been addressed in the latest electron.
