### ISSUE TITLE
Autoreloading css does not work

### ISSUE THREAD

**Issue by ghost** [ducky427/electron-template#3]
It seems that auto reloading css files does not work. But I'm not sure where they should be stored, so it could be a setup issue.  So far I use a css directory below the app dir.

**Comment by ducky427** [comment]
I think this should be solved by using `:css-dirs` in figwheel configuration. I'll add that shortly. 

Thanks for reporting the issue.

**Comment by ducky427** [comment]
I've done a new release of the template with the css reloading support. Let me know if you have any issues.
