### ISSUE TITLE
Module version mismatch. Expected 14, got 44.

### ISSUE THREAD

**Issue by ghost** [ducky427/electron-template#4]
This happens when 'grunt launch' is used. 
Loading "appdmg.js" tasks...ERROR

> > Error: Module version mismatch. Expected 14, got 44.

After that error message  the app is launched and everything seems to work.

**Comment by ducky427** [comment]
I think this error is due to the library being compiled against a different version of node than the one supplied by Electron. More [here](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md)

Could you tell me which OS and node version you are running?

**Comment by ghost** [comment]
I'm using Yosemite and node v0.12.4

**Comment by ducky427** [comment]
I would recommend using io.js v2.3.1 as thats the version of node running in Electron. This is to prevent API/ABI differences between the two node versions.

I personally use [NVM](https://github.com/creationix/nvm) to handle issues like this.

You could alternatively compile the native modules yourself as mentioned in the doc guide.

**Comment by juliousglori** [comment]
Im using iojs-v2.5.0 but still im having trouble with this error, I have a script with a pm2 start command, when i run it manually it starts fine, but when i run it from crontab i encountered this error. What is the difference between manually run the script and run from crontab?

**Comment by ducky427** [comment]
Please reopen this if you think this is still an issue
