### ISSUE TITLE
pm2 start from crontab => Error: Module version mismatch. Expected 14, got 44.

### ISSUE THREAD

**Issue by juliousglori** [ducky427/electron-template#5]
Hi, i want to run pm2 start from crontab whenever my app is down, but im getting error like this when cron executed my script:

App name:maintenance-script id:9 exited with code 255
PM2 Script /home/ubuntu/src/maintenance-script/server/app.js had too many unstable restarts (15). Stopped. "errored"

maintenance-script-9 (err): 2015-09-28 05:55 +00:00: /home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:83
maintenance-script-9 (err):         throw e
maintenance-script-9 (err):               ^
maintenance-script-9 (err): Error: Module version mismatch. Expected 14, got 44.
maintenance-script-9 (err):     at Error (native)
maintenance-script-9 (err):     at Module.load (module.js:349:32)
maintenance-script-9 (err):     at Function.Module._load (module.js:305:12)
maintenance-script-9 (err):     at Module.require (module.js:357:17)
maintenance-script-9 (err):     at require (module.js:373:17)
maintenance-script-9 (err):     at bindings (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
maintenance-script-9 (err):     at Object.<anonymous> (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
maintenance-script-9 (err):     at Module._compile (module.js:449:26)
maintenance-script-9 (err):     at Object.Module._extensions..js (module.js:467:10)
maintenance-script-9 (err):     at Module.load (module.js:349:32)
maintenance-script-9 (err):     at Function.Module._load (module.js:305:12)
maintenance-script-9 (err):     at Module.require (module.js:357:17)
maintenance-script-9 (err):     at require (module.js:373:17)
maintenance-script-9 (err):     at Object.<anonymous> (/home/ubuntu/src/maintenance-script/server/node_modules/co-bcrypt/index.js:1:76)
maintenance-script-9 (err):     at Module._compile (module.js:449:26)
maintenance-script-9 (err):     at Object.Module._extensions..js (module.js:467:10)

Can somebody help me how to figure this out? I am using iojs-v2.5.0.. Thanks in advance

**Comment by ducky427** [comment]
Hi, 
1) What version of Electron are you running? 
2) Is there a reason you are using crontab for launching the app? As I see it, this is a desktop app and not a linux service.

**Comment by ducky427** [comment]
Please reopen this if you think this is still an issue.
