### ISSUE TITLE
How do I configure figwheel REPL with nREPL?

### ISSUE THREAD

**Issue by markjfisher** [ducky427/electron-template#7]
I'm trying to follow the guide at https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl to use cider-jackin to create an nREPL and have figwheel start through that.

However, when I fire up the application I'm getting:

```
Launching development version...
[25530:1130/135339:INFO:renderer_main.cc(200)] Renderer process started
[25526:1130/135339:INFO:CONSOLE(1)] "Uncaught ReferenceError: goog is not defined", source: file:///Users/markf/dev/clojure/electron-template-cljs/app/js/p/app.js (1)
```

and nothing communicates with the figwheel start and I don't see the prompt.

I notice from looking in the chrome debug view of the application it's missing the whole "out/cljs/...." directories and I can only see app.js.

Are there any extra steps in the process that I need to do?
I raised a question on figwheel-lein too at https://github.com/bhauman/lein-figwheel/issues/303

Any help would be greatly appreciated.

**Comment by ducky427** [comment]
thanks a lot for the report @markjfisher. I'll be investigating this. I've only ever used the figwheel repl and not the nREPL. so it may take me a while to figure it out. 

cheers!

**Comment by markjfisher** [comment]
it would be really nice if you do get it working, it's mostly there with the instructions in lein-figwheel. The benefits would be having it running inside emacs and not on the command line, so it then opens out to more tooling.

**Comment by ducky427** [comment]
Hi @markjfisher, I've updated the template with adjustments for getting the nREPL working. I've added a section in the generated readme for it.

The issue I experienced at first were due to non-merging of leiningen profiles as noted in the wiki. Once I fixed those, it was working.

I've also updated the underlying dependencies.

**Comment by markjfisher** [comment]
trying it out now, thanks

**Comment by markjfisher** [comment]
Excellent. It works on cmd line via nrepl as documented, but needed a couple of tweaks for cider-jack-in, as described below.

I created a file "env/dev/cljs/user.clj" with the following:

```
(ns user
  (:use [figwheel-sidecar.repl-api :as ra]))

(def figwheel-config
  {:figwheel-options {:css-dirs ["app/css"]}
   :build-ids ["dev"]
   :all-builds
   [{:id "dev"
     :figwheel {:on-jsload "etest.core/mount-root"}
     :source-paths ["src/cljs" "env/dev/cljs"]
     :compiler {:main "etest.dev"
                :asset-path "js/p/out"
                :output-to "app/js/p/app.js"
                :output-dir "app/js/p/out" }}]})

(defn start [] (ra/start-figwheel! figwheel-config))
(defn stop [] (ra/stop-figwheel!))
(defn cljs [] (ra/cljs-repl "dev"))
```

(obviously the on-jsload needs to change per project)
And adding the following to project.clj:

```
:profiles {:dev ;; ...
                   ;; ...
                   :dependencies [[figwheel-sidecar "0.5.0-2"]
                                  [com.cemerick/piggieback "0.2.1"]]
                   ;; ...
:repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
```

i am now able in emacs to do: C-c M-j (cider-jack-in), then run:

```
user> (start)
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - dev
Compiling "app/js/p/app.js" from ["src/cljs" "env/dev/cljs"]...
Successfully compiled "app/js/p/app.js" in 1.78 seconds.
Figwheel: Starting CSS Watcher for paths  ["app/css"]
#<SystemMap>

user> (cljs)
Launching ClojureScript REPL for build: dev
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (print-config [id ...])         ;; prints out build configurations
          (fig-status)                    ;; displays current state of system
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when Figwheel connects to your application
To quit, type: :cljs/quit
nil
```

Then after doing "grunt launch" on command line, i get the figwheel cljs prompt and can interact with it as below:

```
cljs.user> (+ 1 2)
3
```

Changes to my cljs files are being picked up in the app.

Without the project.clj changes, in emacs you have a continuous "Stdin:" prompt for repl commands in cljs instead of being able to interactively type in the repl window, which is what I believe piggieback fixes.

Many thanks.

**Comment by ducky427** [comment]
Thats excellent!

**Comment by markjfisher** [comment]
Even inspired me to blog about it https://fenrock.wordpress.com/2015/12/01/developing-electron-apps-in-clojurescript-with-emacs-setting-up-guide/

**Comment by ducky427** [comment]
Looks great. I'll add a link to this. :+1:

**Comment by markjfisher** [comment]
_bow_
